version: "3.8"

services:
  app:
    build:
      context: ./turismo-backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      APP_ENV: local
      APP_DEBUG: true
    volumes:
      - ./turismo-backend:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: nginx_laravel
    ports:
      - "8000:80"
    volumes:
      - ./turismo-backend:/var/www
      - ./turismo-backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && ng serve --host 0.0.0.0"

volumes:
  postgres_data:
